#!/usr/bin/env php
<?php

/**
 * A Simple MVC
 * Created by: Albet Novendo
 * File: ASMVC CLI
 * ASMVC is protected by GNU GPL v2.
 */

use Albet\Asmvc\Core\Cli;

/**
 * Define that ASMVC Cli is started.
 */
define('ASMVC_START', true);

/**
 * Calling autoload. If it's not exist. Install composer's autoload.
 */
if (is_dir(__DIR__ . '/vendor/')) {
    require_once __DIR__ . '/App/Core/init.php';
    $install = false;
} else {
    echo "ASMVC akan melakukan instalisasi. Harap pastikan anda memiliki composer dan exec() bisa digunakan\n";
    $install = true;
}
require_once __DIR__ . '/App/Core/Helpers.php';
require_once __DIR__ . '/App/Core/Cli.php';

/**
 * Validate that ASMVC must be running by CLI interface only.
 */
if (PHP_SAPI !== 'cli') {
    exit('ASMVC hanya bisa dijalankan dengan CLI' . PHP_EOL);
}

/**
 * Parsing the argument written by user.
 */
$cli = new Cli;
if ($install) {
    $cli->install();
} else {
    $cli->argument_parse($argv);
}
