#!/usr/bin/env php
<?php

/**
 * A Simple MVC
 * Created by: Albet Novendo
 * File: ASMVC CLI
 * ASMVC is protected by GNU GPL v2.
 */

use Albet\Asmvc\Core\Cli;

define('ASMVC_START', microtime());

/**
 * Memanggil dependecies
 */
if (is_dir(__DIR__ . '/vendor/')) {
    require_once __DIR__ . '/vendor/autoload.php';
    $install = false;
} else {
    echo "ASMVC akan melakukan instalisasi. Harap pastikan anda memiliki composer dan exec() bisa digunakan\n";
    $install = true;
}
require_once __DIR__ . '/App/Core/Helpers.php';
require_once __DIR__ . '/App/Core/Cli.php';

/**
 * Validasi dimana ASMVC dijalankan.
 */
if (PHP_SAPI !== 'cli') {
    exit('ASMVC hanya bisa dijalankan dengan CLI' . PHP_EOL);
}

/**
 * Mendapatkan argument
 */
$cli = new Cli;
if ($install) {
    $cli->install();
} else {
    $cli->argument_parse($argv);
}
