<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'CheckPerformance' => 'get1',
);

    protected function get1()
    {
        return false;
    }

}
